# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87832cf45a75dde96c0f2476b0e8e41345ddca7ef9992f40ad6e0fffb4bd19f73e5e6ed3c7643f62824b444cce89b0e6584b478b2d7ddf61fc2fa99e3fc00b1

test:
  secret_key_base: 8de48be45eefbab83d30a9316a88c18ef1361d94a5042dc218fd7b49b9a90835b31d2ecca4bd6b33c89e5a578fd2e74a1297070f44269d85cd5661f3ccb0d1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
